server:
  port: 8000

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*" # GET 이외의 요청에 필요
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true
      routes:
        # 블로그 서비스
        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/blog/recent/**, /blog/search/**, /blog/profile/**, /blog/posts/**
            - Method=GET
            
        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/blog/**
          filters:
            - AuthorizationHeaderFilter
            
        # 문의 서비스
        - id: inquiry-service
          uri: lb://INQUIRY-SERVICE
          predicates:
            - Path=/inquiries/**
            - Method=GET
            
        - id: inquiry-service
          uri: lb://INQUIRY-SERVICE
          predicates:
            - Path=/inquiries/**
          filters:
            - AuthorizationHeaderFilter
            
        # 모의 면접 서비스
        - id: interview-service
          uri: lb://INTERVIEW-SERVICE
          predicates:
            - Path=/interviews/**
          filters:
            - AuthorizationHeaderFilter
            
        # 회원 및 인증 서비스
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/auth/**, /login/**, /oauth2/**
            
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/members/**
            - Method=GET
          filters:
            - AuthorizationHeaderFilter
            
        # 공지사항 서비스
        - id: notice-service
          uri: lb://NOTICE-SERVICE
          predicates:
            - Path=/notices/**
            
        # 알림 서비스
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - AuthorizationHeaderFilter
            
        # 포트폴리오 서비스
        - id: portfolio-service
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/portfolios/**
          filters:
            - AuthorizationHeaderFilter
            
        # 관심 직군 서비스
        - id: prejobs-service
          uri: lb://PREJOBS-SERVICE
          predicates:
            - Path=/pre-jobs/**
          filters:
            - AuthorizationHeaderFilter
            
        # 자기소개서 서비스
        - id: ps-service
          uri: lb://PS-SERVICE
          predicates:
            - Path=/ps/**
          filters:
            - AuthorizationHeaderFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: blog-service
      url: /blog/v3/api-docs
    urls[1]:
      name: inquiry-service
      url: /inquiries/v3/api-docs
    urls[2]:
      name: interview-service
      url: /interviews/v3/api-docs
    urls[3]:
      name: member-service
      url: /members/v3/api-docs
    urls[4]:
      name: notice-service
      url: /notices/v3/api-docs
    urls[5]:
      name: notification-service
      url: /notifications/v3/api-docs
    urls[6]:
      name: portfolio-service
      url: /portfolios/v3/api-docs
    urls[7]:
      name: prejobs-service
      url: /pre-jobs/v3/api-docs
    urls[8]:
      name: ps-service
      url: /ps/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, beans

jwt:
  secret_key: myaongpplogmyaongpplogmyaongpplogmyaongpplog
