server:
  port: 9087

spring:
  application:
    name: prejobs-service

  datasource:
    url: jdbc:mysql://az-a.prototype.868cb0a4f6be466ba1bd6f12ea9dec18.mysql.managed-service.kr-central-2.kakaocloud.com:3306/prototype
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prototype
    password: prototype
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # eureka 서버에 등록

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api-docs/v3/pre-jobs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  management:
    endpoints:
      web:
        exposure:
          include: refresh, health, info, beans

    jwt:
      secret_key: myaongpplogmyaongpplogmyaongpplogmyaongpplog
