server:
  port: 9087

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

spring:
  application:
    name: prejobs-service

  cloud:
    config:
      enabled: true
    kubernetes:
      config:
        enabled: true
        namespace: popolog
      discovery:
        enabled: true
        all-namespaces: true
      loadbalancer:
        mode: service

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api-docs/v3/pre-jobs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, beans
