server:
  port: 9083

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # eureka 서버에 등록

spring:
  application:
    name: member-service

  cloud:
    kubernetes:
      enabled: false

  data:
    redis:
      host: localhost
      port: 6379 # redis

  datasource:
    url: jdbc:mysql://172.16.210.108:3306/prototype
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: minhyung
    password: Myaong00!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 0ae8c24b64dc00267bd12055e15594e8 # js key
            client-secret: 0ebb5b3b4cd63a88e7a86d0b7bf19f06 # rest api key
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:9083/login/oauth2/code/kakao # 카카오 인증 서버로부터 인가 코드가 전달되는 uri
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
          google:
            client-name: google
            client-id: 395368250733-nrpfnq9o3vird9ligjj5lu1ccj6h75gk.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:9083/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: myaongpplogmyaongpplogmyaongpplogmyaongpplog

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api-docs/v3/members
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, beans, prometheus
      base-path: /temp/
  metrics:
    tags:
      application: ${spring.application.name}


redirect-url:
  reissue: http://localhost:8000/auth/reissue
  main: http://localhost:3000/main
  login: http://localhost:3000/log-in
  profile-form: http://localhost:3000/sign-up/detail